/**
 ** Netlify Function - Sitemap Index
 ** Generates a sitemap index that references all sub-sitemaps
 **
 ** Sitemap Structure:
 ** - /sitemap.xml → This file (sitemap index)
 ** - /sitemap-static.xml → Static pages (generated by custom script at build time)
 ** - /sitemap-blog.xml → Dynamic blog content (generated by sitemap.js function)
 **
 ** This follows Google's recommendation for organizing large sitemaps:
 ** https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps
 */

export default async (request, context) => {
    const siteUrl = process.env.SITE_URL;

    try {
        // Build sitemap index XML
        let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
        xml +=
            '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

        // Add static pages sitemap (generated by custom script at build time)
        xml += '  <sitemap>\n';
        xml += `    <loc>${siteUrl}/sitemap-static.xml</loc>\n`;
        xml += `    <lastmod>${new Date().toISOString()}</lastmod>\n`;
        xml += '  </sitemap>\n';

        // Add blog sitemap (dynamic, updated frequently)
        xml += '  <sitemap>\n';
        xml += `    <loc>${siteUrl}/sitemap-blog.xml</loc>\n`;
        xml += `    <lastmod>${new Date().toISOString()}</lastmod>\n`;
        xml += '  </sitemap>\n';

        xml += '</sitemapindex>';

        return new Response(xml, {
            status: 200,
            headers: {
                'Content-Type': 'application/xml; charset=utf-8',
                'Cache-Control':
                    'public, s-maxage=3600, stale-while-revalidate=86400', // Cache for 1 hour
            },
        });
    } catch (error) {
        console.error('[sitemap-index] Error generating sitemap index:', error);
        return new Response('Error generating sitemap index', {
            status: 500,
            headers: { 'Content-Type': 'text/plain' },
        });
    }
};
