/**
 ** Netlify Function - Blog Sitemap Generator
 ** Generates XML sitemap specifically for dynamic blog content
 ** Fetches blog posts and categories from WordPress
 **
 ** Usage:
 ** /sitemap-blog.xml
 **
 ** This is part of a sitemap index strategy:
 ** - /sitemap.xml → Main sitemap index
 ** - /sitemap-static.xml → Static pages (generated by Netlify plugin)
 ** - /sitemap-blog.xml → This file (dynamic blog content)
 */

export default async (request, context) => {
    const siteUrl = process.env.SITE_URL;
    const wpBaseUrl = process.env.WORDPRESS_API_URL;

    try {
        // Fetch all published posts
        const postsUrl = `${wpBaseUrl}/posts?per_page=100&_embed`;
        const postsResponse = await fetch(postsUrl);
        const posts = postsResponse.ok ? await postsResponse.json() : [];

        // Fetch all categories
        const categoriesUrl = `${wpBaseUrl}/categories?per_page=100`;
        const categoriesResponse = await fetch(categoriesUrl);
        const categories = categoriesResponse.ok
            ? await categoriesResponse.json()
            : [];

        // Build sitemap XML
        let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
        xml +=
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n';

        // Add blog posts with publication date
        posts.forEach(post => {
            const slug = post.slug;
            const modified = new Date(post.modified)
                .toISOString()
                .split('T')[0];
            const featuredImage =
                post._embedded?.['wp:featuredmedia']?.[0]?.source_url || null;

            xml += '  <url>\n';
            xml += `    <loc>${escapeXml(siteUrl + '/blog/' + slug)}</loc>\n`;
            xml += `    <lastmod>${modified}</lastmod>\n`;
            xml += '    <changefreq>weekly</changefreq>\n';
            xml += '    <priority>0.8</priority>\n';

            // Add featured image if available
            if (featuredImage) {
                xml += `    <image:image>\n`;
                xml += `      <image:loc>${escapeXml(featuredImage)}</image:loc>\n`;
                xml += `    </image:image>\n`;
            }

            xml += '  </url>\n';
        });

        // Add blog categories
        categories.forEach(category => {
            // Skip uncategorized
            if (category.slug === 'uncategorized') {
                return;
            }

            const categorySlug = category.slug;
            xml += '  <url>\n';
            xml += `    <loc>${escapeXml(siteUrl + '/blog/c/' + categorySlug)}</loc>\n`;
            xml += `    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>\n`;
            xml += '    <changefreq>weekly</changefreq>\n';
            xml += '    <priority>0.7</priority>\n';
            xml += '  </url>\n';
        });

        xml += '</urlset>';

        return new Response(xml, {
            status: 200,
            headers: {
                'Content-Type': 'application/xml; charset=utf-8',
                'Cache-Control':
                    'public, s-maxage=3600, stale-while-revalidate=86400', // Cache for 1 hour, stale for 24 hours
            },
        });
    } catch (error) {
        console.error('[sitemap-blog] Error generating blog sitemap:', error);
        return new Response('Error generating blog sitemap', {
            status: 500,
            headers: { 'Content-Type': 'text/plain' },
        });
    }
};

/**
 * Escape XML special characters
 * @param {string} str - String to escape
 * @returns {string} Escaped string
 */
function escapeXml(str) {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}
